-- Active: 1685984322357@@localhost@3306@Mypracticals
SHOW TABLES;
SELECT * FROM student_info;
CREATE TABLE student_info(RegNo VARCHAR(20) PRIMARY KEY,FirstName CHAR(20) NOT NULL,MiddleName CHAR(20),Surname CHAR(20) NOT NULL,Date_Of_Birth DATE NOT NULL,Year_Of_Study INT(1) NOT NULL,Semester INT(1) NOT NULL);
INSERT INTO student_info VALUES("BBIT/MG/2545/09/21","SILAS","MUKAGATI","ANGERA","2001.11.30"."BBIT",3,1);
ALTER TABLE student_info DROP Course;
ALTER TABLE student_info ADD Course VARCHAR(10) NOT NULL AFTER Date_Of_Birth;
CREATE TABLE student_account(RegNo VARCHAR(20) PRIMARY KEY,Total_fees DECIMAL(10,2) NOT NULL,Fees_paid DECIMAL(10,2) NOT NULL DEFAULT 0.00, Balance DECIMAL(10,2) AS (Total_fees - Fees_paid));
ALTER TABLE student_performance ADD Foreign Key (RegNo) REFERENCES student_info(RegNo) ON DELETE CASCADE ON UPDATE CASCADE;
SELECT * FROM student_account;
INSERT INTO student_account(RegNo,School,Total_fees,Fees_paid) VALUES ("BBIT/MG/2545/09/21","BUSINESS AND ECONOMICS",30300.00,29000.00);
CREATE TABLE SchoolOfBusiness(DepartmentId VARCHAR(5) PRIMARY KEY,DepartmentName CHAR(30) NOT NULL,NumberOfCourses INT(100) NOT NULL);
CREATE TABLE Commerce(CourseId VARCHAR(10) PRIMARY KEY,CourseName CHAR(100),Units VARCHAR(2000));
CREATE TABLE Units(UnitCode VARCHAR(10) PRIMARY KEY,UnitName CHAR(100) NOT NULL);
CREATE TABLE student_performance(RegNo VARCHAR(20) PRIMARY KEY,UnitCode VARCHAR(10) NOT NULL,UnitName CHAR(100),CAT1 FLOAT NOT NULL,CAT2 FLOAT NOT NULL,FINAL_EXAM FLOAT NOT NULL,AVERAGE FLOAT AS (CAT1+CAT2+FINAL_EXAM), FOREIGN KEY(RegNo) REFERENCES student_info(RegNo));
SELECT * FROM student_performance;
ALTER TABLE student_performance DROP CONSTRAINT student_performance_ibfk_1;
alter table student_performance MODIFY AVERAGE FLOAT AS (CAT_AVERAGE+FINAL_EXAM);
SELECT DISTINCT RegNo 